In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
cars=pd.read_csv("cars-dataset.csv")
cars.head()

C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\884007194.py:1: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  cars=pd.read_csv("cars-dataset.csv")

,Unnamed: 0,Model,Serie,Company,Body style,Segment,Production years,Cylinders,Displacement,Power(HP),...,Nominal Capacity,Top speed (electrical),EV Range,High mpg,Extra high mpg,Medium mpg,Low mpg,Total maximum torque,Maximum Capacity,Specification summary
0,0,AC Ace (1993-1996),Ace,AC,"Convertible (spider/spyder, cabrio/cabriolet, ...",Coupe Cabrio,"1993, 1994, 1995, 1996",V8,4942 cm3,260 HP @ 5250 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9L V8 4AT (260 HP)
1,1,AC Aceca (1998-2000),Aceca,AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5L V8 32V Turbo 6MT (354 HP)
2,2,AC Aceca (1998-2000),Aceca,AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6L V8 5MT (326 HP)
3,3,AC Cobra MkIII (1965-1967),Cobra,AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,4727 cm3,280 HP @ 5800 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7L V8 4MT (280 HP)
4,4,AC Cobra 378 MkIV (1965-1967),Cobra,AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,NaN,446.1 HP @ - RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.2L V8 6MT

In [24]:
cars.isna().sum()

Unnamed: 0                               0
Model                                    0
Serie                                    0
Company                                  0
Body style                            7554
Segment                                  0
Production years                         0
Cylinders                              522
Displacement                           996
Power(HP)                              566
Power(BHP)                             566
Power(KW)                              566
Torque(lb-ft)                         1072
Torque(Nm)                            1072
Electrical motor power               29059
Electrical motor torque              29271
Fuel System                            212
Fuel                                    65
Fuel capacity                         8199
Top Speed                             4433
Acceleration 0-62 Mph (0-100 kph)     5125
Drive Type                             165
Gearbox                                459
Front brake                            309
Rear brake                             320
Tire Size                             2223
Length                                 746
Width                                  731
Height                                 873
Front/rear Track                      1990
Wheelbase                              795
Ground Clearance                      6486
Aerodynamics (Cd)                     8811
Aerodynamics (frontal area)          29637
Turning circle                       26982
Cargo Volume                          3479
Unladen Weight                        2312
Gross Weight Limit                    5453
Combined mpg                          4296
City mpg                              7649
Highway mpg                           7664
CO2 Emissions                         9141
CO2 Emissions (Combined)             29090
Turning circle (curb to curb)        29257
Total maximum power                  29233
Power pack                           29183
Nominal Capacity                     29314
Top speed (electrical)               29594
EV Range                             29285
High mpg                             29549
Extra high mpg                       29555
Medium mpg                           29566
Low mpg                              29537
Total maximum torque                 29396
Maximum Capacity                     29591
Specification summary                    0
dtype: int64

In [25]:
cars.drop("Serie",axis=1)

,Unnamed: 0,Model,Company,Body style,Segment,Production years,Cylinders,Displacement,Power(HP),Power(BHP),...,Nominal Capacity,Top speed (electrical),EV Range,High mpg,Extra high mpg,Medium mpg,Low mpg,Total maximum torque,Maximum Capacity,Specification summary
0,0,AC Ace (1993-1996),AC,"Convertible (spider/spyder, cabrio/cabriolet, ...",Coupe Cabrio,"1993, 1994, 1995, 1996",V8,4942 cm3,260 HP @ 5250 RPM,256 BHP @ 5250 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.9L V8 4AT (260 HP)
1,1,AC Aceca (1998-2000),AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,345 BHP @ 6500 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5L V8 32V Turbo 6MT (354 HP)
2,2,AC Aceca (1998-2000),AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,345 BHP @ 6500 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6L V8 5MT (326 HP)
3,3,AC Cobra MkIII (1965-1967),AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,4727 cm3,280 HP @ 5800 RPM,276 BHP @ 5800 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7L V8 4MT (280 HP)
4,4,AC Cobra 378 MkIV (1965-1967),AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,NaN,446.1 HP @ - RPM,440 BHP @ - RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.2L V8 6MT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29787,29787,2026 Zenvo Aurora Agil,Zenvo,Coupé (two-door),Exotic,2023,V12,NaN,1250 HP @ 9800 RPM,1233 BHP @ 9800 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1032.6 lb-ft (1400 Nm),NaN,6.6L V12 7AT RWD (1471 HP)
29788,29788,2026 Zenvo Aurora Tur,Zenvo,Coupé (two-door),Exotic,2023,V12,NaN,1250 HP @ 9800 RPM,1233 BHP @ 9800 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1253.9 lb-ft (1700 Nm),NaN,6.6L V12 7AT AWD (1876 HP)
29789,29789,Zenvo TS1 (2017-Present),Zenvo,Coupé (two-door),Exotic,"2017, 2018, 2019, 2020, 2021, 2022, 2023",V8,5800 cm3,1118 HP @ 7100 RPM,1103 BHP @ 7100 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.8 V8 7AT (1118 HP)
29790,29790,Zenvo TSR-S (2018-Present),Zenvo,NaN,Exotic,"2018, 2019, 2020, 2021, 2022, 2023",V8,5800 cm3,1193.3 HP @ 7100 RPM,1177 BHP @ 7100 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.8L V8 7AT (1177 HP)
29791,29791,Zenvo ST1 (2009-2017),Zenvo,Coupé (two-door),Exotic,"2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016...",V8,6800 cm3,1104 HP @ 6900 RPM,1089 BHP @ 6900 RPM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.8 V8 7AT (1104 HP)

In [26]:
cols=["Model","Company","Cylinders","Displacement","Power(HP)","Torque(lb-ft)","Fuel","Top Speed","Acceleration 0-62 Mph (0-100 kph)","Specification summary"]

In [27]:
cars.iloc[:,0:21]

,Unnamed: 0,Model,Serie,Company,Body style,Segment,Production years,Cylinders,Displacement,Power(HP),...,Power(KW),Torque(lb-ft),Torque(Nm),Electrical motor power,Electrical motor torque,Fuel System,Fuel,Fuel capacity,Top Speed,Acceleration 0-62 Mph (0-100 kph)
0,0,AC Ace (1993-1996),Ace,AC,"Convertible (spider/spyder, cabrio/cabriolet, ...",Coupe Cabrio,"1993, 1994, 1995, 1996",V8,4942 cm3,260 HP @ 5250 RPM,...,191.2 KW @ 5250 RPM,320 lb-ft @ 3250 RPM,434 Nm @ 3250 RPM,NaN,NaN,Multipoint Injection Naturally aspirated,Gasoline,21.1 gallons (79.9 L),140 mph (225 km/h),NaN
1,1,AC Aceca (1998-2000),Aceca,AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,...,257.4 KW @ 6500 RPM,300 lb-ft @ 4000 RPM,407 Nm @ 4000 RPM,NaN,NaN,Multipoint Injection Naturally aspirated,Gasoline,23.8 gallons (90.1 L),155 mph (249 km/h),5.6 s
2,2,AC Aceca (1998-2000),Aceca,AC,Coupé (two-door),Coupe,"1998, 1999, 2000",V8,3506 cm3,350 HP @ 6500 RPM,...,257.4 KW @ 6500 RPM,300 lb-ft @ 4000 RPM,407 Nm @ 4000 RPM,NaN,NaN,Multipoint Injection Naturally aspirated,Gasoline,23.8 gallons (90.1 L),155 mph (249 km/h),5.6 s
3,3,AC Cobra MkIII (1965-1967),Cobra,AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,4727 cm3,280 HP @ 5800 RPM,...,205.9 KW @ 5800 RPM,314 lb-ft @ 3400 RPM,426 Nm @ 3400 RPM,NaN,NaN,NaN,Gasoline,18 gallons (68.1 L),140 mph (225 km/h),4.7 s
4,4,AC Cobra 378 MkIV (1965-1967),Cobra,AC,Coupé (two-door),Roadster & Convertible,"1965, 1966, 1967",V8,NaN,446.1 HP @ - RPM,...,328.1 KW @ - RPM,NaN,NaN,NaN,NaN,NaN,Gasoline,18 gallons (68.1 L),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29787,29787,2026 Zenvo Aurora Agil,Aurora,Zenvo,Coupé (two-door),Exotic,2023,V12,NaN,1250 HP @ 9800 RPM,...,919.4 KW @ 9800 RPM,NaN,NaN,147.1 kw (200 hp),NaN,Turbocharged Direct Injection,Hybrid Gasoline,NaN,227 mph (365 km/h),2.5 s
29788,29788,2026 Zenvo Aurora Tur,Aurora,Zenvo,Coupé (two-door),Exotic,2023,V12,NaN,1250 HP @ 9800 RPM,...,919.4 KW @ 9800 RPM,NaN,NaN,147.1 kw (200 hp),NaN,Turbocharged Direct Injection,Mild Hybrid,NaN,280 mph (451 km/h),2.3 s
29789,29789,Zenvo TS1 (2017-Present),TS1,Zenvo,Coupé (two-door),Exotic,"2017, 2018, 2019, 2020, 2021, 2022, 2023",V8,5800 cm3,1118 HP @ 7100 RPM,...,822.3 KW @ 7100 RPM,840 lb-ft @ - RPM,1139 Nm @ - RPM,NaN,NaN,Supercharged Multipoint Injection,NaN,NaN,233 mph (375 km/h),2.8 s
29790,29790,Zenvo TSR-S (2018-Present),TSR-S,Zenvo,NaN,Exotic,"2018, 2019, 2020, 2021, 2022, 2023",V8,5800 cm3,1193.3 HP @ 7100 RPM,...,877.7 KW @ 7100 RPM,840 lb-ft @ - RPM,1139 Nm @ - RPM,NaN,NaN,Sequential Fuel Injection,Gasoline,NaN,202 mph (325 km/h),2.8 s
29791,29791,Zenvo ST1 (2009-2017),ST1,Zenvo,Coupé (two-door),Exotic,"2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016...",V8,6800 cm3,1104 HP @ 6900 RPM,...,812 KW @ 6900 RPM,1055 lb-ft @ 4500 RPM,1430 Nm @ 4500 RPM,NaN,NaN,Turbocharged Multipoint Injection,Gasoline,NaN,233 mph (375 km/h),3 s

In [28]:
df=cars[cols]
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Ace (1993-1996),AC,V8,4942 cm3,260 HP @ 5250 RPM,320 lb-ft @ 3250 RPM,Gasoline,140 mph (225 km/h),NaN,4.9L V8 4AT (260 HP)
1,AC Aceca (1998-2000),AC,V8,3506 cm3,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
2,AC Aceca (1998-2000),AC,V8,3506 cm3,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
3,AC Cobra MkIII (1965-1967),AC,V8,4727 cm3,280 HP @ 5800 RPM,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
4,AC Cobra 378 MkIV (1965-1967),AC,V8,NaN,446.1 HP @ - RPM,NaN,Gasoline,NaN,NaN,6.2L V8 6MT

In [29]:
df.isna().sum()

Model                                   0
Company                                 0
Cylinders                             522
Displacement                          996
Power(HP)                             566
Torque(lb-ft)                        1072
Fuel                                   65
Top Speed                            4433
Acceleration 0-62 Mph (0-100 kph)    5125
Specification summary                   0
dtype: int64

In [30]:
df[["Engine Size","Remaining"]]=df["Specification summary"].str.split(" ",n=1,expand=True)
df.drop(columns=["Engine Size"],inplace=True,axis=1)
df.drop(columns=["Remaining"],inplace=True,axis=1)
df.head()

C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\2082119895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["Engine Size","Remaining"]]=df["Specification summary"].str.split(" ",n=1,expand=True)
C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\2082119895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[["Engine Size","Remaining"]]=df["Specification summary"].str.split(" ",n=1,expand=True)
C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\2082119895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Engine Size"],inplace=True,axis=1)
C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\2082119895.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=["Remaining"],inplace=True,axis=1)

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Ace (1993-1996),AC,V8,4942 cm3,260 HP @ 5250 RPM,320 lb-ft @ 3250 RPM,Gasoline,140 mph (225 km/h),NaN,4.9L V8 4AT (260 HP)
1,AC Aceca (1998-2000),AC,V8,3506 cm3,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
2,AC Aceca (1998-2000),AC,V8,3506 cm3,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
3,AC Cobra MkIII (1965-1967),AC,V8,4727 cm3,280 HP @ 5800 RPM,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
4,AC Cobra 378 MkIV (1965-1967),AC,V8,NaN,446.1 HP @ - RPM,NaN,Gasoline,NaN,NaN,6.2L V8 6MT

In [31]:
df["Displacement"]=df["Displacement"].str.replace("cm3","")
df.head()

C:\Users\Jaswanth\AppData\Local\Temp\ipykernel_29636\2266061899.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Displacement"]=df["Displacement"].str.replace("cm3","")

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Ace (1993-1996),AC,V8,4942,260 HP @ 5250 RPM,320 lb-ft @ 3250 RPM,Gasoline,140 mph (225 km/h),NaN,4.9L V8 4AT (260 HP)
1,AC Aceca (1998-2000),AC,V8,3506,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
2,AC Aceca (1998-2000),AC,V8,3506,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
3,AC Cobra MkIII (1965-1967),AC,V8,4727,280 HP @ 5800 RPM,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
4,AC Cobra 378 MkIV (1965-1967),AC,V8,NaN,446.1 HP @ - RPM,NaN,Gasoline,NaN,NaN,6.2L V8 6MT

In [32]:
df.isna().sum()
df=df.dropna()

In [33]:
df["Displacement"]=df["Displacement"].str.strip()
df["Displacement"]=df["Displacement"].str.replace(",","")
df["Displacement"].astype(float).astype(int)

1        3506
2        3506
3        4727
5        4727
20       3664
         ...
29783    3562
29784    2934
29785    3201
29790    5800
29791    6800
Name: Displacement, Length: 23967, dtype: int64

In [34]:
df["Displacement"] = (pd.to_numeric(df["Displacement"], errors='coerce') / 1000).round(1)

In [35]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
1,AC Aceca (1998-2000),AC,V8,3.5,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
2,AC Aceca (1998-2000),AC,V8,3.5,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
3,AC Cobra MkIII (1965-1967),AC,V8,4.7,280 HP @ 5800 RPM,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
5,AC Cobra MkII (1963-1965),AC,V8,4.7,271 HP @ 5800 RPM,312 lb-ft @ 3400 RPM,Gasoline,141 mph (227 km/h),5.3 s,4.7L V8 4MT (271 HP)
20,ACURA MDX (2010-2013),ACURA,V6,3.7,305 HP @ 6300 RPM,270 lb-ft @ 4500 RPM,Gasoline,137 mph (220 km/h),7.3 s,3.7L V6 AWD 6AT (300 HP)

In [36]:
df.reset_index(drop=True,inplace=True)

In [37]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Aceca (1998-2000),AC,V8,3.5,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
1,AC Aceca (1998-2000),AC,V8,3.5,350 HP @ 6500 RPM,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280 HP @ 5800 RPM,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271 HP @ 5800 RPM,312 lb-ft @ 3400 RPM,Gasoline,141 mph (227 km/h),5.3 s,4.7L V8 4MT (271 HP)
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305 HP @ 6300 RPM,270 lb-ft @ 4500 RPM,Gasoline,137 mph (220 km/h),7.3 s,3.7L V6 AWD 6AT (300 HP)

In [38]:
df["Power(HP)"]=df["Power(HP)"].str.replace("HP","")
df["Power(HP)"]=df["Power(HP)"].str.replace("@","")
df["Power(HP)"]=df["Power(HP)"].str.replace("RPM","")

In [39]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Aceca (1998-2000),AC,V8,3.5,350 6500,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
1,AC Aceca (1998-2000),AC,V8,3.5,350 6500,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280 5800,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271 5800,312 lb-ft @ 3400 RPM,Gasoline,141 mph (227 km/h),5.3 s,4.7L V8 4MT (271 HP)
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305 6300,270 lb-ft @ 4500 RPM,Gasoline,137 mph (220 km/h),7.3 s,3.7L V6 AWD 6AT (300 HP)

In [40]:
df["Power(HP)"] = df["Power(HP)"].str.split(" ",expand=True)[0]
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Aceca (1998-2000),AC,V8,3.5,350,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
1,AC Aceca (1998-2000),AC,V8,3.5,350,300 lb-ft @ 4000 RPM,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314 lb-ft @ 3400 RPM,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312 lb-ft @ 3400 RPM,Gasoline,141 mph (227 km/h),5.3 s,4.7L V8 4MT (271 HP)
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270 lb-ft @ 4500 RPM,Gasoline,137 mph (220 km/h),7.3 s,3.7L V6 AWD 6AT (300 HP)

In [41]:
df["Torque(lb-ft)"]=df["Torque(lb-ft)"].str.replace("lb-ft","")
df["Torque(lb-ft)"]=df["Torque(lb-ft)"].str.replace("@","")
df["Torque(lb-ft)"]=df["Torque(lb-ft)"].str.replace("RPM","")
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,155 mph (249 km/h),5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
1,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,155 mph (249 km/h),5.6 s,4.6L V8 5MT (326 HP)
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314 3400,Gasoline,140 mph (225 km/h),4.7 s,4.7L V8 4MT (280 HP)
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312 3400,Gasoline,141 mph (227 km/h),5.3 s,4.7L V8 4MT (271 HP)
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270 4500,Gasoline,137 mph (220 km/h),7.3 s,3.7L V6 AWD 6AT (300 HP)

In [43]:
df["Top Speed"]=df["Top Speed"].str.replace("mph","")
df["Top Speed"]=df["Top Speed"].str.replace("km/h","")
df["Top Speed"]=df["Top Speed"].str.replace("(","")
df["Top Speed"]=df["Top Speed"].str.replace(")","")
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Top Speed,Acceleration 0-62 Mph (0-100 kph),Specification summary
0,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,155 249,5.6 s,3.5L V8 32V Turbo 6MT (354 HP)
1,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,155 249,5.6 s,4.6L V8 5MT (326 HP)
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314 3400,Gasoline,140 225,4.7 s,4.7L V8 4MT (280 HP)
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312 3400,Gasoline,141 227,5.3 s,4.7L V8 4MT (271 HP)
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270 4500,Gasoline,137 220,7.3 s,3.7L V6 AWD 6AT (300 HP)

In [51]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Acceleration 0-62 Mph (0-100 kph),Specification summary,Top Speed(mph),Top Speed(km/h)
0,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,5.6 s,3.5L V8 32V Turbo 6MT (354 HP),155,249
1,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,5.6 s,4.6L V8 5MT (326 HP),155,249
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314 3400,Gasoline,4.7 s,4.7L V8 4MT (280 HP),140,225
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312 3400,Gasoline,5.3 s,4.7L V8 4MT (271 HP),141,227
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270 4500,Gasoline,7.3 s,3.7L V6 AWD 6AT (300 HP),137,220

In [54]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Acceleration 0-62 Mph (0-100 kph),Top Speed(mph),Top Speed(km/h)
0,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,5.6 s,155,249
1,AC Aceca (1998-2000),AC,V8,3.5,350,300 4000,Gasoline,5.6 s,155,249
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314 3400,Gasoline,4.7 s,140,225
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312 3400,Gasoline,5.3 s,141,227
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270 4500,Gasoline,7.3 s,137,220

In [56]:
df["Torque(lb-ft)"] = df["Torque(lb-ft)"].str.split(" ",expand=True)[0]

In [58]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Acceleration 0-62 Mph (0-100 kph),Top Speed(mph),Top Speed(km/h)
0,AC Aceca (1998-2000),AC,V8,3.5,350,300,Gasoline,5.6 s,155,249
1,AC Aceca (1998-2000),AC,V8,3.5,350,300,Gasoline,5.6 s,155,249
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314,Gasoline,4.7 s,140,225
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312,Gasoline,5.3 s,141,227
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270,Gasoline,7.3 s,137,220

In [60]:
df["Acceleration 0-62 Mph (0-100 kph)"]=df["Acceleration 0-62 Mph (0-100 kph)"].str.replace("s","")

In [62]:
df.head()

,Model,Company,Cylinders,Displacement,Power(HP),Torque(lb-ft),Fuel,Acceleration 0-62 Mph (0-100 kph),Top Speed(mph),Top Speed(km/h)
0,AC Aceca (1998-2000),AC,V8,3.5,350,300,Gasoline,5.6,155,249
1,AC Aceca (1998-2000),AC,V8,3.5,350,300,Gasoline,5.6,155,249
2,AC Cobra MkIII (1965-1967),AC,V8,4.7,280,314,Gasoline,4.7,140,225
3,AC Cobra MkII (1963-1965),AC,V8,4.7,271,312,Gasoline,5.3,141,227
4,ACURA MDX (2010-2013),ACURA,V6,3.7,305,270,Gasoline,7.3,137,220

In [63]:
df.to_csv("cars_Data_Cleaned.csv")